on:
  push:
    branches:
      - master
name: Build My App
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get the latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "::set-output name=LATEST_TAG::$latest_tag"

      - name: Increment tag version
        id: increment_tag
        run: |
          new_tag=v$(echo ${{ steps.get_tag.outputs.LATEST_TAG }} | awk -F. '{print $1"."$2"."$3+1}')
          echo "::set-output name=NEW_TAG::$new_tag"

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: ${{ steps.increment_tag.outputs.NEW_TAG }}
          token: ${{ secrets.TOKEN }}

